### ISSUE TITLE
`elcoq--sertop-observe`:  (args-out-of-range 272 272)

### ISSUE THREAD

**Issue by ejgallego** [cpitclaudel/elcoq#2]
Steps to reproduce:
1. Queue up the `test.v`.
2. Insert a few blank lines at the end of the document, call `elcoq--sertop-observe`.

If you call observe a bit closer it works.

**Comment by cpitclaudel** [comment]
Yup :) Subject of http://emacs.stackexchange.com/questions/23970/how-do-i-get-the-closest-property-change-before-a-given-point/23989 asked yesterday.

That question didn't yield the nice fix that I was hoping for though, so I'll add a workaround.

Dio you get the async stuff working though? (my secret hope is that you might even find this useful for experimenting with SerAPI ^^)

**Comment by cpitclaudel** [comment]
Btw, if you want to play with the XML protocol, there's a basic xml repl in this repo as well (xmltop.el). You'll need to set the `xmltop-executable-path` to your coqtop binary for it to work. After that, you can run it with xmltop. It produces output in SEXP notation, parsed from the XML. I find it a bit nicer that rlwrap + coqtop in a regular terminal.

**Comment by ejgallego** [comment]
I see, thanks! Indeed I much prefer elcoq to experiment with SerAPI than having to go through manual processes! The async stuff is mostly working I think, however it is quite experimental even upstream.

**Comment by cpitclaudel** [comment]
Yup, I think it's very close to working. One difference that I see with CoqIDE is that in CoqIDE all the correct proofs progress to Qed after `observe`ing the end of the file.

**Comment by ejgallego** [comment]
Yeah something is going on. My guess on what is happening thou is that indeed the workers are not launched anymore. 

This used to work before, but I can't see now where the problem is :S

**Comment by ejgallego** [comment]
Clément, what apporach should we use for debugging in elcoq? Can you redirect stderr to a buffer?

**Comment by cpitclaudel** [comment]
Yup, definitely. I'll implement that soon.

**Comment by ejgallego** [comment]
yeah the sequence of protocol calls seems the same than CoqIDE. The problem is somehow the STM is refusing to launch workers, because some magic went off... At least the good news is that it used to work!

**Comment by ejgallego** [comment]
Re: sterr:
Cool thanks!

**Comment by cpitclaudel** [comment]
The output thing is done; I merged in the relevant parts of sertop.el and made sure that the queries were shown as well. Next time you run elcoq-run it will pop up a debug buffer.

Hopefully this helps! I'm glad I can contribute to the development of SerAPI this way ^^

**Comment by ejgallego** [comment]
Cool! Indeed it'll help a lot, thanks! I need to hit the bed now and will be a bit busy the next days; but I've managed to understand why the workers where not launched, see the last commit in SerAPI.

With this, test.v now behaves as in CoqIDE. Still, as Enrico pointed out the old behavior was indeed intended so it is really a configuration thing.

Also, it is not hard to hit what seem bugs in the async code. The IDEs workaround that by killing stray workers, we need to see what we can do. Cheers!
