### ISSUE TITLE
ascii recording video

### ISSUE THREAD

**Issue by ejgallego** [cpitclaudel/elcoq#5]
Hi! I'm actually citing `elcoq` in a report / paper, and after checking the page I see the ASCII video was archived.

IMHO it would be nice to have it restored if possible, for archive / documentation purposes.

**Comment by cpitclaudel** [comment]
I have emailed the admins to ask for the video to be unarchived.  I didn't realize at the time that they had automatic archiving.

**Comment by cpitclaudel** [comment]
Fixed, the video got resurrected https://asciinema.org/a/b84ph360841x3c9lwq6pyihm9
